"""initial migration

Revision ID: 00001
Revises:
Create Date: 2026-09-20 23:27:07.036504

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "00001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE venues (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name        TEXT NOT NULL UNIQUE,
            timezone    TEXT NOT NULL,
            address     TEXT NOT NULL,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE users (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email       TEXT NOT NULL UNIQUE,
            name        TEXT NOT NULL,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE events (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name        TEXT NOT NULL UNIQUE,
            venue_id    INTEGER NOT NULL REFERENCES venues(id),
            starts_at   TIMESTAMPTZ NOT NULL,
            ends_at     TIMESTAMPTZ NOT NULL,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE seats (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            section     TEXT NOT NULL,
            seat_row    TEXT NOT NULL,
            seat_number TEXT NOT NULL,
            venue_id    INTEGER NOT NULL REFERENCES venues(id),
            created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (venue_id, section, seat_row, seat_number)
        );

        CREATE TABLE ticket_types (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tier        TEXT NOT NULL,
            event_id    INTEGER NOT NULL REFERENCES events(id),
            created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (event_id, tier)
        );

        CREATE TABLE tickets (
            id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            price           INTEGER NOT NULL CHECK (price >= 0),
            held_until      TIMESTAMPTZ,
            sold_at         TIMESTAMPTZ,
            seat_id         INTEGER NOT NULL REFERENCES seats(id),
            event_id        INTEGER NOT NULL REFERENCES events(id),
            held_by_user_id INTEGER REFERENCES users(id),
            sold_to_user_id INTEGER REFERENCES users(id),
            ticket_type_id  INTEGER NOT NULL REFERENCES ticket_types(id),
            created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (event_id, seat_id)
        );

        CREATE TABLE orders (
            id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            status              TEXT NOT NULL,
            user_id             INTEGER NOT NULL REFERENCES users(id),
            subtotal            INTEGER NOT NULL CHECK (subtotal >= 0),
            tax_amount          INTEGER NOT NULL CHECK (tax_amount >= 0),
            total_charged       INTEGER NOT NULL CHECK (total_charged >= 0),
            tax_rate_applied    REAL NOT NULL CHECK (tax_rate_applied >= 0),
            tax_jurisdiction    TEXT NOT NULL,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE order_items (
            order_id    INTEGER NOT NULL REFERENCES orders(id),
            ticket_id   INTEGER NOT NULL UNIQUE REFERENCES tickets(id),
            created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (order_id, ticket_id)
        );

        CREATE TABLE tax_rates (
            id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            jurisdiction    TEXT NOT NULL,
            tax_type        TEXT NOT NULL,
            rate            REAL NOT NULL CHECK (rate >= 0),
            effective_from  TIMESTAMPTZ NOT NULL,
            effective_to    TIMESTAMPTZ,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CHECK (effective_to IS NULL OR effective_to > effective_from),
            UNIQUE (jurisdiction, tax_type, effective_from)
        );

        CREATE INDEX idx_events_venue_id ON events(venue_id);
        CREATE INDEX idx_seats_venue_id ON seats(venue_id);
        CREATE INDEX idx_ticket_types_event_id ON ticket_types(event_id);
        CREATE INDEX idx_tickets_seat_id ON tickets(seat_id);
        CREATE INDEX idx_tickets_ticket_type_id ON tickets(ticket_type_id);
        CREATE INDEX idx_orders_user_id ON orders(user_id);
        CREATE INDEX idx_order_items_ticket_id ON order_items(ticket_id);
        CREATE INDEX idx_tax_rates_lookup
            ON tax_rates(jurisdiction, tax_type, effective_from, effective_to);
    """)


def downgrade() -> None:
    op.execute("""
        DROP TABLE IF EXISTS order_items;
        DROP TABLE IF EXISTS orders;
        DROP TABLE IF EXISTS tickets;
        DROP TABLE IF EXISTS ticket_types;
        DROP TABLE IF EXISTS seats;
        DROP TABLE IF EXISTS events;
        DROP TABLE IF EXISTS tax_rates;
        DROP TABLE IF EXISTS users;
        DROP TABLE IF EXISTS venues;
    """)
